### ISSUE TITLE
Error creating repositories

### ISSUE THREAD

**Issue by devcamcar** [cloudfoundry-community/gogs-boshrelease#1]
Hello, I just deployed gogs using this bosh release on an OpenStack environment. Things appeared to work initially and I was able to complete the setup phase.  Creating users and configuring works well but when I tried to create a repository I received the following error:

```
2015/02/26 20:02:24 ESC[1;36m[T] action.NewRepoAction: devcamcar/test2ESC[0m
[Macaron] ESC[1;36mCompleted /repo/create 500 Internal Server Error in 81.375203msESC[0m
2015/02/26 20:02:24 ESC[1;31m[repo.go:128 CreatePost()] [E] CreatePost: initRepository: git push: remote: /usr/bin/env: bash: No such file or directory
remote: error: hook declined to update refs/heads/master
To /var/vcap/store/gogs/repositories/devcamcar/test2.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to '/var/vcap/store/gogs/repositories/devcamcar/test2.git'
ESC[0m
```

Any suggestions?

**Comment by lnguyen** [comment]
hi there, I haven't seen that error personally or able to reproduce it. I did cut a new release that does handle ssh better, can you delete vm and try deploying new version? 

Can I take a look at your manifest? I use postgres job with mine and pick that it in install, not sure if that effect its.

**Comment by jrbudnack** [comment]
@devcamcar Hi!  I was able to recreate your error.  I can look into it further, but for now, a workaround I found is I am able to push repo updates via SSH instead of http.

**Comment by jrbudnack** [comment]
@devcamcar I found the problem.  The vcap user needed `/bin` to be in its path in order for it to run the git hooks (it was choking on the shebang line).  I'll be submitting the fix shortly, should be included in the next release, which should be cut pretty soon.
