### ISSUE TITLE
Using routing.yml but advertising URL is http://localhost/...

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/gogs-boshrelease#11]
![screen shot 2017-08-21 at 10 36 25 pm](https://user-images.githubusercontent.com/108/29519557-418613ee-86c1-11e7-9d88-e3d2dca4c20f.png)

**Comment by ntdt** [comment]
This issue is addressed by commit f4554b33c60cc333ddf955a7e62af26ebed23688
URL with http is good, but SSH one does not show port correctly.
