### ISSUE TITLE
offline installation not possible

### ISSUE THREAD

**Issue by deltatree** [cloudfoundry-community/gogs-boshrelease#6]
It is not possible to install gogs-boshrelease in an environment without internet access.
Is there a trick to do that?

**Comment by norman-abramovitz** [comment]
Can you give some more details about where in your install process you are having issues?

**Comment by alexanelli** [comment]
@deltatree just checking in to see if this would still be helpful; Thanks :)

**Comment by ntdt** [comment]
If you can generate the bosh release with option --with-tarball, then you can deploy without access internet by doing bosh deploy tarball.tgz
